### ISSUE TITLE
usePersistStorage.d.ts

### ISSUE THREAD

**Issue by cdsaidev** [visuallylab/react-native-use-persist-storage#10]
Line 12: Has a typo 'type'
it's set to `false ` when it should be `boolean`
` sensitive?: false | RNSensitiveInfoOptions;` 
should be 
` sensitive?: boolean | RNSensitiveInfoOptions;`

**Comment by TseHang** [comment]
Hi @chris9753 ,
I think it still should be `false`, since it can not be `true`.
Ideally, it only accepts `RNSensitiveInfoOptions`, and if not it should be `false`  or `undefined`.
I think the type is correct. Thanks your report.
