### ISSUE TITLE
No Way To Clear Storage

### ISSUE THREAD

**Issue by akanshSirohi** [visuallylab/react-native-use-persist-storage#13]
There is no way to clear all values stored in the persistent storage...

**Comment by TseHang** [comment]
Hi @akanshSirohi, 

1. You can set `{ options: { persist: false } }`  in each hook to disable asyncStorage and  remove values stored in persist storage. ([see](https://github.com/visuallylab/react-native-use-persist-storage#options-see))

2. If you want to clear *all values* when app initialized, you can use [setPersistStorageDefaults](https://github.com/visuallylab/react-native-use-persist-storage/blob/master/src/defaultOptions.ts#L20) and give default options `{ persist: false }` .

When set `persist: false`, it will remove values stored in persist storage automatically.

Thanks your report, hope it can help you! ：）

**Comment by akanshSirohi** [comment]
Thanks buddy!
