### ISSUE TITLE
Add Provider instructions to createPersistContext docs

### ISSUE THREAD

**Issue by dsernst** [visuallylab/react-native-use-persist-storage#29]
The `createPersistContext` helper function is great. But following the docs, I was stuck for about 30 minutes trying to debug what was missing, why weren't my changes updating the state? 

Eventually I realized it was because I hadn't added `<PersistContext.Provider>` around my app. I know it does mention this in the "Context Usage" section, but the docs make it seem like `createPersistContext` handles all that boilerplate automatically. It wasn't obvious w/o serious digging to figure out what was missing.

**Comment by TseHang** [comment]
Thanks @dsernst , nice suggestion. 😃
